AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - cobra_commander.gemspec

Metrics/ClassLength:
  Exclude:
    - spec/**/*.rb
    - cobra_commander.gemspec

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: true

Layout/ExtraSpacing:
  Exclude:
    - cobra_commander.gemspec

Layout/SpaceAroundOperators:
  Exclude:
    - cobra_commander.gemspec

Style/Lambda:
  EnforcedStyle: literal

Layout/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them when introducing an interpolation.
# Use single quotes only if their semantics are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
